name: Build Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu
        override: true

    - name: Install linker for Windows
      run: sudo apt-get update && sudo apt-get install -y mingw-w64

    - name: Build EXE
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: rust-windows-exe
        path: target/x86_64-pc-windows-gnu/release/rust-to-exe.exe
